views: ['C10095_rgb']
clip_size: 1800
target_label: 'action'
learning_rate: 0.01
weight_decay: 0.005
scheduler_step: 100
classes: 202
batch_size: 16
test_batch_size: 1
cemse_alpha: 0.17
train_epochs: 200
frame_features: 2048
pose_joint_features: 3
pose_joint_count: 42
model_dim: 500
dropout: 0.20
temporal_layers_count: 3
temporal_state_dim: 1000